app = 'domestique-redis'
primary_region = 'iad'

[build]
  image = 'redis:7-alpine'

[processes]
  app = "redis-server --dir /data --save 60 1 --appendonly no --maxmemory 64mb --maxmemory-policy allkeys-lru"

[mounts]
  source = "redis_data"
  destination = "/data"

[[services]]
  protocol = 'tcp'
  internal_port = 6379
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 6379

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '256mb'
